/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package productosapp;

/**
 *
 * @author cata.orellana
 */
public class FrameBienvenida extends javax.swing.JFrame {

    /**
     * Creates new form FrameBienvenida
     */
    public FrameBienvenida() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        linkListar = new javax.swing.JMenuItem();
        linkAgregar = new javax.swing.JMenuItem();
        linkEditar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(153, 204, 0));
        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenido al Almacén de Productos");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productosapp/database-512.png"))); // NOI18N

        jMenu1.setText("Abrir");

        linkListar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        linkListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productosapp/people.png"))); // NOI18N
        linkListar.setText("Listar");
        linkListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkListarActionPerformed(evt);
            }
        });
        jMenu1.add(linkListar);

        linkAgregar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        linkAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productosapp/plus.png"))); // NOI18N
        linkAgregar.setText("Agregar");
        linkAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkAgregarActionPerformed(evt);
            }
        });
        jMenu1.add(linkAgregar);

        linkEditar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        linkEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/productosapp/pencil.png"))); // NOI18N
        linkEditar.setText("Modificar / Eliminar");
        linkEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkEditarActionPerformed(evt);
            }
        });
        jMenu1.add(linkEditar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acerca de");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setText("Nuestra Empresa");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNuestraEmpresa(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem5.setText("Salir");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(207, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(181, 181, 181))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(244, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void linkListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkListarActionPerformed
        // TODO add your handling code here:
        // new FrameListarProductos().setVisible(true);
        new FrameListarProductos().setVisible(true);
    }//GEN-LAST:event_linkListarActionPerformed

    private void menuItemNuestraEmpresa(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNuestraEmpresa
        // TODO add your handling code here:
        new FrameNuestraEmpresa().setVisible(true);
        
    }//GEN-LAST:event_menuItemNuestraEmpresa

    private void linkAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkAgregarActionPerformed
        // TODO add your handling code here:
        new FrameCrearProducto().setVisible(true);
    }//GEN-LAST:event_linkAgregarActionPerformed

    private void linkEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkEditarActionPerformed
        // TODO add your handling code here:
        new FrameModificarEliminarProducto().setVisible(true);
    }//GEN-LAST:event_linkEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameBienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameBienvenida().setVisible(true);
                ApiProducto api = new ApiProducto();
                // datos de prueba
                // api.createProducto("0", "prueba1", "una marca", "un modelo", "100", "2016-01-01");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem linkAgregar;
    private javax.swing.JMenuItem linkEditar;
    private javax.swing.JMenuItem linkListar;
    // End of variables declaration//GEN-END:variables
}
